# Generated by Django 2.2.12 on 2021-03-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='post',
            field=models.CharField(default='not add', max_length=50),
        ),
    ]
